 
/** dropdown_options_s indexes **/
db.getCollection("dropdown_options_s").ensureIndex({
  "_id": NumberInt(1)
},[
  
]);

/** dropdown_options_s records **/
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("561bc4eb083f1177158b4567"),
  "name": "position",
  "options": [
    "Seller",
    "Buyer",
    "Seller & Buyer",
    "Company Owner",
    "Administration Staff",
    "CEO Staff",
    "Logistic",
    "Company Attorney",
    "Other Position"
  ],
  "lang": "en",
  "type": "drop_down"
});
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("561bc66e083f11ba158b4567"),
  "name": "relation_with_gdoox",
  "options": [
    "Gdoox Agent",
    "Sales Representative",
    "Promoter",
    "Consultant",
    "Staff",
    "Technical Support"
  ],
  "lang": "en",
  "type": "dropdown"
});
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("5620fdce083f11d8248b4567"),
  "name": "company_dimension",
  "options": [
    "Single Trader",
    "Employees1",
    "Employees2-4",
    "Employees5-9",
    "Employees10-15",
    "Employees16-25",
    "Employees26-50",
    "Employees51-100",
    "Employees101-150",
    "Employees151-250",
    "Employees251-500",
    "Employees501-750",
    "Employees751-1000",
    "Employees>1000"
  ],
  "lang": "en"
});
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("5620ffbf083f113a258b4567"),
  "name": "activity_type",
  "options": [
    "Trading",
    "Services",
    "Maintenance",
    "Consultance & Intelectual",
    "Individual services"
  ],
  "lang": "en"
});
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("56210098083f116d1b8b4567"),
  "name": "business_operation",
  "options": [
    "Manufacture",
    "Distributor",
    "Reseller",
    "Vendor",
    "other"
  ],
  "lang": "en"
});
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("562102de083f117b258b4567"),
  "name": "payment_accepted",
  "options": [
    "Documents against Acceptance",
    "Document against Payment",
    "WesternUnion",
    "Letter of credit",
    "Wire Transfer",
    "Money Grant",
    "PayPal",
    "scrow"
  ],
  "lang": "en"
});
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("562107cd083f1179218b4567"),
  "name": "market",
  "options": [
    "Local",
    "National",
    "International",
    "Continental",
    "Intercontinental",
    "Worldwide"
  ],
  "lang": "en"
});
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("562e0752083f11d41c8b4567"),
  "name": "payment_method",
  "options": [
    "Skrill",
    "Amazon Payments",
    "American Express",
    "Paypal",
    "Authorize.net"
  ]
});
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("562611a0083f1197208b4567"),
  "name": "credit_card",
  "options": [
    "VISA",
    "DINES",
    "MASTER CARD",
    "AMERICAN EXPRESS"
  ],
  "lang": "en"
});
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("561bc566083f110e088b4567"),
  "name": "countries",
  "options": [
    "Abkhazia",
    "Afghanistan",
    "Akrotiri/Dhekelia",
    "Albania",
    "Alderney",
    "Algeria",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua/Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Ascension Island",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas, The",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire",
    "Bosnia/Herzegovina",
    "Botswana",
    "Brazil",
    "British Indian Ocn ",
    "British Virgin Is",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burma",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman ",
    "Central African Rep.",
    "Chad",
    "Chile",
    "China",
    "Cocos Islands",
    "Colombia",
    "Comoros",
    "Congo, Dem Rep",
    "Congo, Rep",
    "Cook Islands",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czech Rep",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Rep",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Polynesia",
    "Gabon",
    "Gambia, The",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia ",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Nagorno-Karabakh ",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Northern Cyprus",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn Islands",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saba",
    "Sahrawi ",
    "Saint Helena",
    "Saint Kitts/Nevis",
    "Saint Lucia",
    "St Vincent/Grenadine",
    "Samoa",
    "San Marino",
    "São Tomé and Príncipe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Eustatius",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "Somaliland",
    "South Africa",
    "South Georgia/South Sandwich Is",
    "South Ossetia",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Transnistria",
    "Trinidad and Tobago",
    "Tristan da Cunha",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Is",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "UAE",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vatican City",
    "Vietnam",
    "Wallis and Futuna",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ],
  "lang": "en",
  "type": "drop_down"
});
db.getCollection("dropdown_options_s").insert({
  "_id": ObjectId("5620fb94083f11be1a8b4567"),
  "name": "organization",
  "options": [
    "Individual Company",
    "--Agricultural Chemicals--",
    "Aluminum",
    "Chemicals - Major Diversified",
    "Copper",
    "Gold",
    "Independent Oil & Gas",
    "Industrial Metals & Minerals",
    "Major Integrated Oil & Gas",
    "Nonmetallic Mineral Mining",
    "Oil & Gas Drilling & Exploration\t",
    "Oil & Gas Equipment & Services",
    "Oil & Gas Pipelines",
    "Oil & Gas Refining & Marketing",
    "Silver",
    "Specialty Chemicals\t",
    "Steel & Iron",
    "Synthetics",
    "Other agriculture",
    "Other Chemicals",
    "--Consumer Goods--",
    "Appliances",
    "Auto & Parts",
    "Beverages - Brewers",
    "Business Equipment",
    "Cigarettes",
    "Cleaning Products",
    "Confectioners",
    "Dairy Products\t",
    "Electronic Equipment",
    "Farm Products\t",
    "Food - Major Diversified",
    "Home Furnishings & Fixtures\t",
    "Housewares & Accessories\t",
    "Meat Products\t",
    "Office Supplies\t",
    "Packaging & Containers",
    "Paper & Paper Products",
    "Personal Products",
    "Photographic Equipment & Supplies",
    "Processed & Packaged Goods\t",
    "Recreational Goods, Other",
    "Recreational Vehicles",
    "Rubber & Plastics",
    "Sporting Goods",
    "Textile - Apparel Clothing",
    "Textile - Apparel Footwear & Accessories\t",
    "Tobacco Products, Other\t",
    "Toys & Games\t",
    "Trucks & Other Vehicles",
    "Other consumer goods\t",
    "--Financial--",
    "Asset Management",
    "Debt Equity Foreing services",
    "Credit Services",
    "Diversified Investments",
    "Insurance Brokers\t",
    "Investment Brokerage - National",
    "Investment Brokerage - Regional\t",
    "Life Insurance",
    "Mortgage Investment",
    "Property Management",
    "Real Estate investment Trust",
    "Real Estate Development",
    "Savings & Loans\t",
    "Other financial",
    "--Healthcare--",
    "Biotechnology",
    "Diagnostic Substances",
    "Drug Delivery",
    "Health Care Plans",
    "Home Health Care",
    "Hospitals",
    "Long-Term Care Facilities\t",
    "Medical Appliances & Equipment\t",
    "Medical Instruments & Supplies",
    "Medical Laboratories & Research",
    "Medical Practitioners",
    "Specialized Health Services",
    "Other healthcare companies",
    "--Industrial Goods--",
    "Aerospace/Defense - Major Diversified\t",
    "Aerospace/Defense Products & Services\t",
    "Cement",
    "Diversified Machinery",
    "Farm & Construction Machinery",
    "General Building Materials",
    "General Contractors",
    "Heavy Construction",
    "Industrial Electrical Equipment",
    "Industrial Equipment & Components",
    "Lumber, Wood Production",
    "Machine Tools & Accessories",
    "Manufactured Housing\t",
    "Metal Fabrication",
    "Pollution & Treatment Controls",
    "Residential Construction",
    "Small Tools & Accessories",
    "Textile Industrial",
    "Waste Management\t",
    "Other industrial goods\t",
    "--Services--",
    "Advertising Agencies",
    "Air Delivery & Freight Services",
    "Air Services, Other",
    "Apparel Stores",
    "Auto Dealerships\t",
    "Auto Parts Stores",
    "Auto Parts Wholesale",
    "Basic Materials Wholesale",
    "Building Materials Wholesale",
    "Business Services",
    "CATV Systems",
    "Computers Wholesale",
    "Consumer Services",
    "Department Stores",
    "Discount, Variety Stores",
    "Drug Stores",
    "Education & Training Services",
    "Electronics Stores",
    "Electronics Wholesale",
    "Entertainment - Diversified",
    "Food Wholesale",
    "Gaming Activities",
    "General Entertainment\t",
    "Grocery Stores",
    "Home Furnishing Stores",
    "Home Improvement Stores",
    "Industrial Equipment Wholesale",
    "Jewelry Stores",
    "Lodging",
    "Management Services",
    "Marketing Services",
    "Medical Equipment Wholesale",
    "Movie Production, Theaters",
    "Music & Video Stores",
    "Personal Services",
    "Railroads",
    "Rental & Leasing Services",
    "Research Services",
    "Resorts & Casinos",
    "Restaurants\t",
    "Security & Protection Services\t",
    "Shipping",
    "Specialty Eateries",
    "Specialty Retail, Other",
    "Sporting Activities",
    "Sporting Goods Stores",
    "Staffing & Outsourcing Services",
    "Technical Services",
    "Toy & Hobby Stores\t",
    "Trucking",
    "Wholesale, Other",
    "Other companies services",
    "--Technology--",
    "Application Software",
    "Business Software & Services",
    "Communication Equipment",
    "Computer Based Systems",
    "Computer Peripherals",
    "Data Storage Devices",
    "Diversified Communication Services",
    "Diversified Computer Systems",
    "Diversified Electronics",
    "Healthcare Information Services",
    "Information & Delivery Services",
    "Information Technology Services",
    "Internet Information Providers\t",
    "Internet Service Providers",
    "Internet Software & Services",
    "Long Distance Carriers\t",
    "Multimedia & Graphics Software",
    "Networking & Communication Devices",
    "Personal Computers",
    "Printed Circuit Boards",
    "Processing Systems & Products",
    "Scientific & Technical Instruments",
    "Security Software & Services",
    "Semiconductors",
    "Technical & System Software",
    "Telecom Services - Domestic",
    "Telecom Services - Foreign",
    "Wireless Communications",
    "Other technologies",
    "--Utilities--",
    "Diversified Utilities",
    "Electric Utilities",
    "Gas Utilities",
    "Water Utilities",
    "Other Utilities",
    "--GDOOX--",
    "Gdoox  National Partner",
    "Gdoox Local Distributor\t"
  ],
  "lang": "en"
});
